SDK_DEMO_PATH ?= .
BL_SDK_BASE ?= $(SDK_DEMO_PATH)/../aithinker_Ai-M6X_SDK

export BL_SDK_BASE

CHIP ?= bl616
BOARD ?= bl616dk
CROSS_COMPILE ?= /home/feilong/Program-ext/aipi/AiPi-Open-Kits/aithinker_Ai-M6X_SDK/toolchain/bin/riscv64-unknown-elf-

# add custom cmake definition
#cmake_definition+=-Dxxx=sss
COMX ?= /dev/ttyACM0

include $(BL_SDK_BASE)/project.build